/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package corgui;

import java.awt.Color;

/**
 *
 * @author Administrator
 */
public class ReadWindow extends javax.swing.JFrame {

    /**
     * Creates new form ReadWindow
     */
    public ReadWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        readTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        signoutButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        readEnrollment = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        gobackmenu = new javax.swing.JButton();
        readAYTerm = new javax.swing.JButton();
        readSchedule = new javax.swing.JButton();
        readFees = new javax.swing.JButton();
        readProgram = new javax.swing.JButton();
        readSection = new javax.swing.JButton();
        readScholarship = new javax.swing.JButton();
        readSubject = new javax.swing.JButton();
        readStudent = new javax.swing.JButton();
        readTuition = new javax.swing.JButton();
        readTuitonFees = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        readTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        readTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(readTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 0, 640, 720));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(112, 0, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        signoutButton.setFont(new java.awt.Font("OldSansBlack", 0, 36)); // NOI18N
        signoutButton.setForeground(new java.awt.Color(255, 255, 255));
        signoutButton.setText("Sign out");
        signoutButton.setBorder(null);
        signoutButton.setBorderPainted(false);
        signoutButton.setContentAreaFilled(false);
        signoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                signoutButtonMouseEntered(evt);
            }
        });
        signoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signoutButtonActionPerformed(evt);
            }
        });
        jPanel4.add(signoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 196, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/signout.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 30, 100));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Read Record");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 100));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 100));

        readEnrollment.setBackground(new java.awt.Color(255, 255, 255));
        readEnrollment.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        readEnrollment.setText("SHOW ENROLLMENT TABLE");
        readEnrollment.setBorder(null);
        readEnrollment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readEnrollmentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readEnrollmentMouseExited(evt);
            }
        });
        readEnrollment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readEnrollmentActionPerformed(evt);
            }
        });
        jPanel3.add(readEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 250, 70));

        jPanel6.setBackground(new java.awt.Color(112, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/menu.png"))); // NOI18N
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 30, 50));

        gobackmenu.setFont(new java.awt.Font("OldSansBlack", 0, 24)); // NOI18N
        gobackmenu.setForeground(new java.awt.Color(255, 255, 255));
        gobackmenu.setText("Go back to Menu");
        gobackmenu.setBorderPainted(false);
        gobackmenu.setContentAreaFilled(false);
        gobackmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobackmenuActionPerformed(evt);
            }
        });
        jPanel6.add(gobackmenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 220, 50));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 670, 1290, 50));

        readAYTerm.setBackground(new java.awt.Color(255, 255, 255));
        readAYTerm.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        readAYTerm.setText("SHOW A.Y - TERM TABLE");
        readAYTerm.setBorder(null);
        readAYTerm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readAYTermMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readAYTermMouseExited(evt);
            }
        });
        readAYTerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readAYTermActionPerformed(evt);
            }
        });
        jPanel3.add(readAYTerm, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 250, 70));

        readSchedule.setBackground(new java.awt.Color(255, 255, 255));
        readSchedule.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        readSchedule.setText("SHOW SCHEDULE TABLE");
        readSchedule.setBorder(null);
        readSchedule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readScheduleMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readScheduleMouseExited(evt);
            }
        });
        readSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readScheduleActionPerformed(evt);
            }
        });
        jPanel3.add(readSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 250, 70));

        readFees.setBackground(new java.awt.Color(255, 255, 255));
        readFees.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        readFees.setText("SHOW FEES TABLE");
        readFees.setBorder(null);
        readFees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readFeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readFeesMouseExited(evt);
            }
        });
        readFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readFeesActionPerformed(evt);
            }
        });
        jPanel3.add(readFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 250, 70));

        readProgram.setBackground(new java.awt.Color(255, 255, 255));
        readProgram.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        readProgram.setText("SHOW PROGRAM TABLE");
        readProgram.setBorder(null);
        readProgram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readProgramMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readProgramMouseExited(evt);
            }
        });
        readProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readProgramActionPerformed(evt);
            }
        });
        jPanel3.add(readProgram, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 250, 70));

        readSection.setBackground(new java.awt.Color(255, 255, 255));
        readSection.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        readSection.setText("SHOW SECTION TABLE ");
        readSection.setBorder(null);
        readSection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readSectionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readSectionMouseExited(evt);
            }
        });
        readSection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readSectionActionPerformed(evt);
            }
        });
        jPanel3.add(readSection, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 250, 70));

        readScholarship.setBackground(new java.awt.Color(255, 255, 255));
        readScholarship.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        readScholarship.setText("SHOW SCHOLARSHIP TABLE");
        readScholarship.setBorder(null);
        readScholarship.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readScholarshipMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readScholarshipMouseExited(evt);
            }
        });
        readScholarship.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readScholarshipActionPerformed(evt);
            }
        });
        jPanel3.add(readScholarship, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, 250, 70));

        readSubject.setBackground(new java.awt.Color(255, 255, 255));
        readSubject.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        readSubject.setText("SHOW SUBJECT TABLE");
        readSubject.setBorder(null);
        readSubject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readSubjectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readSubjectMouseExited(evt);
            }
        });
        readSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readSubjectActionPerformed(evt);
            }
        });
        jPanel3.add(readSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 540, 250, 70));

        readStudent.setBackground(new java.awt.Color(255, 255, 255));
        readStudent.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        readStudent.setText("SHOW STUDENT TABLE");
        readStudent.setBorder(null);
        readStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readStudentMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readStudentMouseExited(evt);
            }
        });
        readStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readStudentActionPerformed(evt);
            }
        });
        jPanel3.add(readStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 250, 70));

        readTuition.setBackground(new java.awt.Color(255, 255, 255));
        readTuition.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        readTuition.setText("SHOW TUITION TABLE");
        readTuition.setBorder(null);
        readTuition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readTuitionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readTuitionMouseExited(evt);
            }
        });
        readTuition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readTuitionActionPerformed(evt);
            }
        });
        jPanel3.add(readTuition, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 250, 70));

        readTuitonFees.setBackground(new java.awt.Color(255, 255, 255));
        readTuitonFees.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        readTuitonFees.setText("SHOW TUITION FEES TABLE");
        readTuitonFees.setBorder(null);
        readTuitonFees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readTuitonFeesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readTuitonFeesMouseExited(evt);
            }
        });
        readTuitonFees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readTuitonFeesActionPerformed(evt);
            }
        });
        jPanel3.add(readTuitonFees, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 250, 70));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 720));

        setSize(new java.awt.Dimension(1296, 759));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void signoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signoutButtonMouseEntered

    }//GEN-LAST:event_signoutButtonMouseEntered

    private void signoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signoutButtonActionPerformed
        
    }//GEN-LAST:event_signoutButtonActionPerformed

    private void gobackmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobackmenuActionPerformed
        MenuOptions menuOptions = new MenuOptions();
        menuOptions.show(); //display frame called

        dispose();
    }//GEN-LAST:event_gobackmenuActionPerformed

    private void readEnrollmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readEnrollmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readEnrollmentActionPerformed

    private void readEnrollmentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readEnrollmentMouseEntered
        readEnrollment.setBackground(new Color(112, 0, 0));
        readEnrollment.setForeground(Color.WHITE);
    }//GEN-LAST:event_readEnrollmentMouseEntered

    private void readEnrollmentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readEnrollmentMouseExited
        readEnrollment.setBackground(Color.WHITE);
        readEnrollment.setForeground(Color.BLACK);
    }//GEN-LAST:event_readEnrollmentMouseExited

    private void readAYTermMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readAYTermMouseEntered
        readAYTerm.setBackground(new Color(112, 0, 0));
        readAYTerm.setForeground(Color.WHITE);
    }//GEN-LAST:event_readAYTermMouseEntered

    private void readAYTermMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readAYTermMouseExited
        readAYTerm.setBackground(Color.WHITE);
        readAYTerm.setForeground(Color.BLACK);
    }//GEN-LAST:event_readAYTermMouseExited

    private void readAYTermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readAYTermActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readAYTermActionPerformed

    private void readScheduleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readScheduleMouseEntered
        readSchedule.setBackground(new Color(112, 0, 0));
        readSchedule.setForeground(Color.WHITE);
    }//GEN-LAST:event_readScheduleMouseEntered

    private void readScheduleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readScheduleMouseExited
        readSchedule.setBackground(Color.WHITE);
        readSchedule.setForeground(Color.BLACK);
    }//GEN-LAST:event_readScheduleMouseExited

    private void readScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readScheduleActionPerformed

    private void readFeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readFeesMouseEntered
        readFees.setBackground(new Color(112, 0, 0));
        readFees.setForeground(Color.WHITE);
    }//GEN-LAST:event_readFeesMouseEntered

    private void readFeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readFeesMouseExited
        readFees.setBackground(Color.WHITE);
        readFees.setForeground(Color.BLACK);
    }//GEN-LAST:event_readFeesMouseExited

    private void readFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readFeesActionPerformed

    private void readProgramMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readProgramMouseEntered
        readProgram.setBackground(new Color(112, 0, 0));
        readProgram.setForeground(Color.WHITE);
    }//GEN-LAST:event_readProgramMouseEntered

    private void readProgramMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readProgramMouseExited
        readProgram.setBackground(Color.WHITE);
        readProgram.setForeground(Color.BLACK);
    }//GEN-LAST:event_readProgramMouseExited

    private void readProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readProgramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readProgramActionPerformed

    private void readSectionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readSectionMouseEntered
        readSection.setBackground(new Color(112, 0, 0));
        readSection.setForeground(Color.WHITE);
    }//GEN-LAST:event_readSectionMouseEntered

    private void readSectionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readSectionMouseExited
        readSection.setBackground(Color.WHITE);
        readSection.setForeground(Color.BLACK);
    }//GEN-LAST:event_readSectionMouseExited

    private void readSectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readSectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readSectionActionPerformed

    private void readScholarshipMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readScholarshipMouseEntered
        readScholarship.setBackground(new Color(112, 0, 0));
        readScholarship.setForeground(Color.WHITE);
    }//GEN-LAST:event_readScholarshipMouseEntered

    private void readScholarshipMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readScholarshipMouseExited
        readScholarship.setBackground(Color.WHITE);
        readScholarship.setForeground(Color.BLACK);
    }//GEN-LAST:event_readScholarshipMouseExited

    private void readScholarshipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readScholarshipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readScholarshipActionPerformed

    private void readSubjectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readSubjectMouseEntered
        readSubject.setBackground(new Color(112, 0, 0));
        readSubject.setForeground(Color.WHITE);
    }//GEN-LAST:event_readSubjectMouseEntered

    private void readSubjectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readSubjectMouseExited
        readSubject.setBackground(Color.WHITE);
        readSubject.setForeground(Color.BLACK);
    }//GEN-LAST:event_readSubjectMouseExited

    private void readSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readSubjectActionPerformed

    private void readStudentMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readStudentMouseEntered
        readStudent.setBackground(new Color(112, 0, 0));
        readStudent.setForeground(Color.WHITE);
    }//GEN-LAST:event_readStudentMouseEntered

    private void readStudentMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readStudentMouseExited
        readStudent.setBackground(Color.WHITE);
        readStudent.setForeground(Color.BLACK);
    }//GEN-LAST:event_readStudentMouseExited

    private void readStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readStudentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readStudentActionPerformed

    private void readTuitionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readTuitionMouseEntered
        readTuition.setBackground(new Color(112, 0, 0));
        readTuition.setForeground(Color.WHITE);
    }//GEN-LAST:event_readTuitionMouseEntered

    private void readTuitionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readTuitionMouseExited
        readTuition.setBackground(Color.WHITE);
        readTuition.setForeground(Color.BLACK);
    }//GEN-LAST:event_readTuitionMouseExited

    private void readTuitionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readTuitionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readTuitionActionPerformed

    private void readTuitonFeesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readTuitonFeesMouseEntered
        readTuitonFees.setBackground(new Color(112, 0, 0));
        readTuitonFees.setForeground(Color.WHITE);
    }//GEN-LAST:event_readTuitonFeesMouseEntered

    private void readTuitonFeesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readTuitonFeesMouseExited
        readTuitonFees.setBackground(Color.WHITE);
        readTuitonFees.setForeground(Color.BLACK);
    }//GEN-LAST:event_readTuitonFeesMouseExited

    private void readTuitonFeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readTuitonFeesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readTuitonFeesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReadWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReadWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReadWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReadWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReadWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton gobackmenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton readAYTerm;
    private javax.swing.JButton readEnrollment;
    private javax.swing.JButton readFees;
    private javax.swing.JButton readProgram;
    private javax.swing.JButton readSchedule;
    private javax.swing.JButton readScholarship;
    private javax.swing.JButton readSection;
    private javax.swing.JButton readStudent;
    private javax.swing.JButton readSubject;
    private javax.swing.JTable readTable;
    private javax.swing.JButton readTuition;
    private javax.swing.JButton readTuitonFees;
    private javax.swing.JButton signoutButton;
    // End of variables declaration//GEN-END:variables
}
